Rename bakery script
neighborhoods/Bakery pull request #1
Opened 2018-11-01 19:45 UTC by jakemalachowski

Remove .php suffix
Add shebang line so it can be run without the leading `php`

2018-11-01 20:40 UTC, rhift approved these changes
awesome catch, ty

2018-11-02 15:05 UTC, rhift requested changes
nit pick

2018-11-02 15:19 UTC, rhift approved these changes
aces, ty

2018-11-02 15:46 UTC, nleapai approved these changes

2018-11-02 15:51 UTC, merged